apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siyuan-data
  labels:
    app.kubernetes.io/name: siyuan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi