---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: siyuan-secrets
  namespace: siyuan
spec:
  encryptedData:
    access-auth-code: AgCawl6dHs8SbTxa0jZwzDeJYt5d/v69XIZEheV2PgI87GFFcgLC9BCErrACE5lNJqynoB/CtrnbPFHpFdIh+wZR3GZ1NNcYskgnheUadishGBZta7ZzxLsDwwaTtGsjuWvmqcQw23aLmpAUCte4BuBeIEcqQl86a6XeIb0+J1cPCNLcKVZJsejWtDMOidrL2ILMY45wFhMgm+hw0Ks0cYqnQ6PPAatM4+UN4NIDQYbUPhpC2GqxmFPcJczCBvdngw8B4QSUWb+J4F8llwBBwCrFXvpFZM6kXp38GFxdNjli0NLY+ZNcPPVD//jvvgSWxduwZXX5ZtBqKSTNvo0C3qg58rVx4Jb+002KT+x9pb9QiMf9pUCUNh58AtiSLDmd4KMLb4tpahmRf1oZaqFLqp95KPUjeY6n4zaTiOv+W2F0YISo9twfjYZcU5gc8yogQBNNt8KLeggkDXuHK6Dhju8se0n4nuZbP9pXlhWDfRjeo3ZI7OVUqu+FZUTsQZcHXywQImicK54DF5tlpeFaiAqgvSna6MxGc307SIrRUsy84WhbNwNe+onhxtawFKZ7CdXf+4CEHuWxetKt2YJJxfacXpryTXe/Da5QqfhfSoeuilXQssjDbH+ZPtuM3LmQ1qxcxKMdD8WbwDAozPBE/T3nxdQ9sLQ6hvnlghf1/2mMru+cwGAtJZTksCBd6F7bEDwVcKcNXWasQCPgQruIBptNfg==
  template:
    metadata:
      name: siyuan-secrets
      namespace: siyuan
