---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: siyuan-secrets
  namespace: siyuan
spec:
  encryptedData:
    access-auth-code: AgAp0qjH63krmRke/zaVAb5ZPg53RqU92Fr5lJ3Dl1a+7D7RhhCU0qA5alctOakcsAXJasrCUCvb4jb/tiO0LDnSaYhQp7Nwwy9fqLEd5NVwHvvwtUxQ5dkDsTgrxEUl3yN3Vai/vWyT0i2AHTYoAvIBPpkb+Fx+gR3rkJnuapa8fVcsqAI5WjYiwFKaICupucQ91QvryIkCcx30bsay43DvYJ/+xpsZLPLYKrmyJ5aoJwL3SSfgmz+SacSZ6lVg6kjhR14pKMGGfny1bxZUsvxQ1VzZpyfw5FC/5tLyiCdP23cV0a78dPN244EP2/bPGaASP6jPdyLHPHAqu9N+i4IHmzww7rXZhw63dPYg9jWT+OWr4RRXRWTdogUw85px323UoO+yI0taV6TQ22eLqn5Y6pt1i9ZAUMLd+HlPApHmrM/NVeP4rHQP0U94FmBaW9BlAGuYcT1CFEEXPmaAig1MK4ecVSjVgDtNu5scbSTmtyd9rCcblYPNdMsn3LhpyRMqGFCcLxCBaysLtMRjE2b5Pc942yxyJMZvI0wM7jNp5zjTDwhoPrg0uF6WKqNfDuwAl4EtmnQyH1JLAuemaxSGhxckzJmQnPQlpbhpebLiQBzGcWWuvnmNRx2igEdGbi3wBX7K7CUBWK0VJ9fJmcnHZXdazYO0uCmtZ6QaO/ES+8b4sb+8EG/IcILwj9t+PedLuARVXS0tRGYGEsChosDLmA==
  template:
    metadata:
      name: siyuan-secrets
      namespace: siyuan
