---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: siyuan-secrets
  namespace: siyuan
spec:
  encryptedData:
    access-auth-code: AgDDwILSekbgWRH1zMszchhzNMRREsqcnsZ8nudnTEtBHpCkmzL8P7GRJoOU3iSbS2Ib8qjljtITAfjXd31xhMY+pzO9TjY2bFEAbVhg5UQKGujU2UdkrU/c/qwZmUwrmClyrzqpLooJQzEcGs3lpFXsBjkgqqC5opWz2H90wmgu1LE9Paf+wZjVBqsB1SmSZAXLrmeQcHF18b4OXh5lS5R6pClYpEAYXFYhqrZhT3YBEQL8NSw6irasSR0ipvOgJKoLMRJ6v9nLrKwWkvskVqwEABywh/cbrGl1w+vE0m2oxBQyho82+sWWK2re561Swe9mD2+Vn6QlA3LVX7VgZjV4SPmdYG/E3NXqORowgX25HmxaHHNBqru6CdN5/fJXVYSZY/cFAQU5IYNUvOjercLvnsd1YC067ba5wjlE5NAzx+trMq/o+thiOisB3OY4vHrx+RC+hBuU0NrvqI/bxhYIArr/FS9rx1vN+Zw7ugBvQOlmSKV/zxPUQzEVSu6wIrXHcUwTWOANDSLCMZC5Dngvk65fS04XC0fnOIMqQsMDbl79fvhp38svBtUsbDuDzvnh/6GTacH+e18R0CKmJSMGjXE/6VHottfBmPsrlYMu/1FIQ/nGSpFLCkNq+pG4GR6NdHyISLXHcAIK1zJ0mfZ8MLGXzd9AsPW9RPaLmWRmiLVe86uH+J8Nu1qPX49j9gmyIl/TQTJ4lqPSYVaz0OAG4w==
  template:
    metadata:
      name: siyuan-secrets
      namespace: siyuan
