apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paseo
resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - pvc-home.yaml
  - pvc-workspace.yaml
  - httproute.yaml
