apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paseo-workspace
  labels:
    app.kubernetes.io/name: paseo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
