---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paseo-secrets
  namespace: paseo
spec:
  encryptedData:
    paseo-password: AgAxUrLiO+DC5Z6TPP6sB1Yt65F9QcXy9w0CzftDT9IE9Zromt2WcuA958FpHfQe+Kk3B40sq4N5w2eql+kR//UpyUvNBii6WFRKq0zfoIT1ly4ovg6rvY0HkX/f38syy4XzUUisbA0iK7Owt8ut3HsXVRYQ7zMjppWk3jNoPG1o+uCiuOeiocoCJsLNS/rjcE8TS6/hZerKbRIKwYx5/6gNcg//GIBj60fAmSGobVMDDZ5Uu9fVBgprL6ZTyNcNIyfRnmXQF9ud+fZ8YVKsL4XFUKC4TcJwvu06gl0mL3udyQaT6e2LlnFlh+vNF+rG9UYTB+3DrHmkQMwokxYpFJd7h6cD7Z6g0FPISd7c6rXiFtrcVIPqMUhXbTUcaVM6cfzh2+WNGQ3pdvkJMwX/oi7PU4nhSqGC8Om0j579Sy3NctQTeiyPk/2mqForWOqfuFmom/eHrmX2/eRo3AcAJMEXlubF4LWQUMzDYJ3IKcGEFgL8pZPq//69cxndS2mZfMv4lef+LrxwNWG8jfWm5akSJKB/Us7EixDqQ8/u+833KPCcgpYOV2SBS/d1wraLnIxIhq0RHJJPAYWz3m/89NqG4bjE1XFJjOnlUq81KXKvMujmzgEjd3HXvlW3EJ/B7Ca9kmMfu8ivtlglDIvgY2dzZzuxPHsu0asQp1XvIcPDIwo3FnRsrIp/YTHUE8u4pXrWu5A6F5TCW+LU0go=
  template:
    metadata:
      name: paseo-secrets
      namespace: paseo
