---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paseo-secrets
  namespace: paseo
spec:
  encryptedData:
    paseo-password: AgBT8lVrUv72Urumj1JQM3MrVHB3xIfyZNVozrqqovrzc0qjZDuVr0NRM1RBPS3vNT16GXUaQJEY1rZX4ZQcbZR+zIZ6hDa7xr+Wr9rE4a4Bf7o70v7Qy1xoqXyqqzM84ZrO55OP1GToQlO5lJ3H/C5ZVAHHgGHxHqGnGC3NLyrnMjiioDktrNxOoMT5xrtOw4A+5Pu4AChiYszbFeR4ACZ2n+DXgKqVFybDmxGZ55vek3Vobtfbt+nPBHnQo7mL0i6Wtw5jr8bgwqwpmgsK6FwWO6aRpSJ9+QlAdAuDPZc2r577SNRkJhNlL+6VFaLVQ7LN88Y4h4wKgeh3r3X5zADuFU158XcPoGEea7Y7SMQQyNWKImSJ5Fq1A8ymZGQpD61ImBVwq8NwepUg0PNJHLhPYJkmpYa4ofpa7RVqEm1LkDec+d8qIPNYlhU+CMLcsn8dAnS0J3mER6EneX4rL0LJ4I8HCmhztBGBsBwzXNhDD5LzVDJ88FuFWb70qkPfM87MxjWtw+/uJn3PRL01dXfBPAMk8/MCU3I4S8DggoOL3HEOGGyNOf3rCN39I2N1KwY8xjiWP8xFSffsJA06g3NVUw47DBRIBtC7Xl1lDoXVNs0s+VmUCZHvG8gPF+eMVlzcSYwtC31iPrtKyv4IDGfINIkkK/IsMHlmtNN8nsab+YokQxyE3KpTOOzQPbsF+plEcVBhOgSmDwSOFAxGX96Hnj9XHqrDRZ0=
  template:
    metadata:
      name: paseo-secrets
      namespace: paseo
