---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: protonvpn-secret
  namespace: media
spec:
  encryptedData:
    SERVER_NAMES: AgBIV7whQ1O/GCRpnNQcBywxn3OiSpgWFfghgzwJfS1Mp8XesrK/V60fQrtxKPg7vCs4Fwe+I3mVaquuSl9bUpd8aSeFQY3euajIv6dltqsOSV/Sof9vIa6q5HQ6g9MkfgEvKtFDXZAZhZMGe25VAhqOTakRX7SomYIbMBWLPzeeRC/oSe2yt6hzcp4vnCoeO/VrWV+TF7N518sIoN0hKIDlMXKip8kacF8bK14WXWjHEZ7pD7cnag/g0YGzs/8PczL2eLAPpnYm4BEh3PZtvD7O33Xz6Ze6JosI9C7HVWHH7lX/o0fomm6EeXR6ncOSdv1HMdc2V42tFjjivadIb8RD7VZVZXuPPT9bn4xz+23on1JowP/Yd/36boG79Ei/hisIqAlt2pIi/flZblCFQGEIj8aGCqwLNZVsKzEI7JN2MOywMC+xs0i183C08AneX/EdIFtBnIKGegsFL0srg4EBI8GQUS8VW1pp9pkKswZhdUG5cXlsFNBflOpVhmEpgYSqK/nMZsIWM5EhSK09dFVjYEtgpb9MIYbLMXG/OZLXJDwchmS5ySy/c9GOw3LnGKxdDl7XZtBs+d7zDPAtbLmzdIoGQHmSHROp53tj+b3V7fTWF7BXJjQJVrgzRjbYovkWIZUcezvqpMwhgI7HAsj1Eyb++IiVXRZYqzbrHO3Isy/Left5aR/t7p7SUILD28ysq1CKIQc=
    WIREGUARD_PRIVATE_KEY: AgB6uzvcYuuuyfwvPzlK69zUb4C5ZvqVvA4ASbq+88h3TB5ZOdnegc8C7+iA5VgTPjsEatY5TaDh4GR9kuTMs3beo6x2AgUaAhpQk/7Z7jGRXJlu17liAjRIhs+W1+gM5O0kJSZpNaGavjL2OEaup+JWu87MX1JVRrGCKwPpKVN0Mtoqsjza8zWFb6W4Y3xsDjI2A3lNEIb+8aEF03Tg52b1KFkvctr0XSBr7oObsNr8+tR/TTlbNhKtzJvFV4TGa9UCgtpGfmVJiWqkih5z2rqLdVgm49rdBiVsZYhReiSrJwmBsYJWDw9c5N5oMdOhlbTHMyEellM1gfBkJA58GEbkIoRK/h97MpRdl5EVFZ4rC/QmRDHFoBa7sVzdfVbDCgInIqo5a4wV1aqLL6y6O9lpb/NZ5/Y8uPabTnUKV1EItS4Ne/jSaR0k44z6tncK+bYuuyGRavvUWnx5EXDeXIXKLSsNWoZYQjs4cvWVs2uvvo2nPOsPVNs1Pra0+IqJjIhRPLR2X8SBJ3rX3e6LdvdWLN4T0Qz7EJhnXOvlU8e1Ox7Tm59Z6F9lvDr5MGCvTiAWxi8/wzJSuEtuSx9ToTyYHE5sQoBTgxB0jZDEVXnU+nHf6YZ4wCjvsoqnKGAxZxo6K2ZVmrdPiMPnFwWrMMW3eo8ZukDHn2yFIP+GhBKya6Rav7KLoUdOGxKYdoGyyxaOhdfQXpygWpazyU5ADt61Na5xNAIZ09Jn26y5u/TqQ05KjJpVPVaHKQ7rAw==
  template:
    metadata:
      name: protonvpn-secret
      namespace: media
