---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: protonvpn-secret
  namespace: media
spec:
  encryptedData:
    SERVER_NAMES: AgBma/WeO34s9ALOMYeu3T+BvIehUQLl1ybK3dNwNj5DLTLHwCDZ4WzsEuZxNPsIgqxv2yVbHdANswrzuh2WsS5RqsXafb9MtgC0huZYmR/hBito2QpZ8lvVk0U9P5aXwUM0wB1vKVaS4CFc+fpS7eWTTyLJWae8UfakodsTN7gjw62nr14X57vsD0eH9hUYYb+T24SORU9kd2yl44KdtHr4bU58Esc0iduIXa/kZ6F6ZRHfEIpdL5AU1UH5fzqV0QZOnPkfA4q3YAYOlTHFM8PlapR0LUI2KCQnsVpXa1/SbprruCBU8XgAKSN28pzbVn0rAS3qNABCnphloOCUhxY5KR0r6ygg7BZFaHvvBK+/DG9imWzwPdKETMRr+5//ihmIOxsigKsrNyHjy8gXlPPkrJxURPRxD4Nh0arLO/SDybheHkBJJyvXuXSfKqCal923pSAsNhjPahx2CQkZna9LMetPLorAd5dDRbwygT2Vzy63CJyQMKw5dkDY4XsP5ZtNKOfx80w5Zo1oLqlOSDtOt7h9EtMwAKhHJkk4jNP7IHhuAWePl9IbeOCHRFS5Q+/1jAnGbZT2xQynC1gcHN8Ka50Jl5ok5ixShu2jxbjkhxX8RU3WKW3zTl32AxzCur4eJmv1/vh9FOEY8GWtjdzMKY6N5JWXZnAvsgl4K0LwZbJMdwRsEx3mgrdkfdSkfctfcjEKDTQ=
    WIREGUARD_PRIVATE_KEY: AgAfENRfbhIq9zSTTcxsF7vZ6KSWtuI8rlao4F+43/sODeCRBREthVy/pIvx9t8dfAFGQRUKMCy2HDhCwdCuXB944WisHrJCz1Iu0nutnl7xMbZ3lADXyRocVc7QiA6/X/AfDd35atZRFcFuCe/2EE3FBo6r+stYDQQGZz6/stNntgCofaqsnh3dvb2UJOOf6qs0iqc4QIEf3WWGAeyIBaTWkgu3p2PiR1VNqNypUHeZwAwHWQOQhXH6X1uOdaFWLzDLlBxu4poLG0Z701Qtdg5AE6TCZ1o12eKtXRiz+e6J7brPW2Y7iCJyuDLQ7FvjzX5jRZEQ6fcxiif4J009ziOZ1cTg24FN7zcSoFsfF2xF+5u4JBoETinS+3CRPL1cbZWiz5s4+rcKwPkZWsguWZuw8672BI4T6KbFaQCJt0DxwbEooMSftEaLpry23xYgysPwNdEzWquQ6xvtzIzITnCqo61xH5pwIWbnQ/IYeCNb/F+ib9fG9IlOdTuKbX7sj9iLhMTTCDnozH9xl7esiZgoofIwKHxPeZAnUPS56lkBMvvw5+TVQCoEey1g5mSSE3MLlINBAXpkr3Wx3syl+M7vVGe2IOJlmoIaNM3wMjRwFfRivjbEhsv3amlxawfXYvgbH9NF7wvmL+e2ctFLUR/TLaOtGGZuOUmFwrjCyLyc4vEnkwLe9Y4pJGknzWAnLFJ2NYUVUYIWGW1+EpgV+QSrSshfhVxZkreelpP7ZXBl4CLVX9yLiWzA7hlOcg==
  template:
    metadata:
      name: protonvpn-secret
      namespace: media
