apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: media
  labels:
    app.kubernetes.io/name: flaresolverr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8191
      protocol: TCP
  selector:
    app.kubernetes.io/name: flaresolverr
