# cf . https://fluxcd.io/flux/guides/image-update/#configure-image-update-for-custom-resources
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: website
  namespace: website
spec:
  image: docker.io/nathanfouere/website
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: website
  namespace: website
spec:
  imageRepositoryRef:
    name: website
  policy:
    semver:
      range: 0.0.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: website
  namespace: website
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
  update:
    path: ./
    strategy: Setters
