apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: website
  namespace: website
spec:
  releaseName: website
  chart:
    spec:
      chart: website
      version: "0.1.5"
      sourceRef:
        kind: HelmRepository
        name: website
  interval: 5m
  install:
    remediation:
      retries: 3
