---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-api-keys
  namespace: openclaw
spec:
  encryptedData:
    ZAI_API_KEY: AgAujDt8TYSdz1IolMyCBv+Bw1lcwcfapT6c1iMNFlAE+Vpz/XweMl1XioTg8NRooxSsx7SLAC38tMOYH4Y2GIc2KC/XYXfcBDDXNibYeHx6/G0a/ICr5HXvaqmQq+zgcYcQxNjJCf2BRPpuxhbSoxJKHx6NR59IJ9v4SeAR5lj3mBLW1NnRqysIxIn9AFIPZZM+oDZvzDU4SUyHFQUYLgOKfNqtFC0f+6u1jtoQAx9NVX3c4Atxfy+Xm5EWGz1ehhVD7um/fDDdNjpG59rqLrFBfLRCSudv1rAC+ZnkIALbsJ35Ce55s9rV/9p5GEhs6rcvE4t4ef0AN+rZ/E/VU3QzXdOCrPbzvL1dVNfWvvlQe+q3uvhfMoGSxJG44UsxjaqhBOvf+gvKlgv/OAYGK0wkxdVay1YVNgNcOWaujH7OKsSLLBxtlmwKRNWfdNrATKTndZHnwdqTG01/wdWWJQDuGj+4X24Gw8KIbPo8vBy4MlGH1PdVGPLXUUx3DzzVSVXLCg/YuIqSh3cmpeW7/b2q3T6VR9NnzkAwkKV+ggK8o9Ma+nko/H0VQi3JiDMIMxiVOT0FClP0oKLKNyMJ+dXCHIigfxnHtBOcV6J7THh7N9Hu29zF5nXBJAXdqld1PubXx1bSiXm/jmRBhGOPv1xw9MxuMzNrUOiujIxUi3RIf0goF26TcwHT9yII6i2XtvEf1oFyruTBzIm1WV9Dp/qcRwPQyEiMm29KbR7RlIcMXVlh1UxJ0kO99R2lElFcxSrV
  template:
    metadata:
      name: openclaw-api-keys
      namespace: openclaw
