apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/siyuan
  - ../base/baikal
  - ../base/website
  - ../base/media-center
  - ../base/blogmanon
patches:
  - path: website-values.yaml
    target:
      kind: HelmRelease
      name: website
