apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/strategia
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
  - path: strategia-values.yaml
    target:
      kind: HelmRelease
      name: strategia
