apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/strategia
  - ../base/siyuan
  - ../base/president-challenge
  - ../base/baikal
  - ../base/website
patches:
  - path: strategia-values.yaml
    target:
      kind: HelmRelease
      name: strategia
  - path: president-challenge-values.yaml
    target:
      kind: HelmRelease
      name: president-challenge
