apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: president-challenge
  namespace: president-challenge
spec:
  values:
    server:
      image:
        repository: nathanfouere/president-challenge-server
        pullPolicy: Always
        tag: "main"

    client:
      image:
        repository: nathanfouere/president-challenge-client
        pullPolicy: Always
        tag: "main"
