apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: website
  namespace: website
spec:
  values:
    image: nathanfouere/website:0.0.1 # {"$imagepolicy": "website:website"}
    pullPolicy: Always
