apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: strategia
  namespace: strategia
spec:
  interval: 5m
  url: oci://registry-1.docker.io/nathanfouere/strategia:0.1.0
  type: oci
