apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-data
  labels:
    app.kubernetes.io/name: baikal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi