---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-secrets
  namespace: flux-system
spec:
  encryptedData:
    bearerToken: AgBHF6rNRixkllMzWqtdIu6aTvU2q/8Caentgs5iX9d09Axy4tYxFKu617rqn+h0PViQg7hnk8bPww7qWWzAjJnAGJfu5V41NHjaUDQDcLqmVPgM98wwTnGkKsez2M0/ukGBkqXF3SMs2PNq2cTR3qOfOlntkbibqSB2n6mWAzy9uHIIITLdZs3h9siaSfW9mtEquUM0qOqFafXwbOncEgSPLMoHecccF9KSNb3waOtDdwwZJJqilB++kl2uu4+Uz9DA513qedFkMMPta2d74zI9YE1x+KrB9rFfDFGOdvXOGChe3bxFr9sDvajtE9gmXF3GkTJRF4pQZb2qZrnicZiz/kcUReg3MMiCPGjjKFKZTjW49gzko30oOfdYTHd88kgx2DONlQ1Op0YcA2aghPvGlhISjQdZ7dHTA+CF77Q1US7MFY8QPOcQeNLVqOx/ezxK6/ZKQLw+CFPEkWBbaeKc1zc5bWMAwGBHLgnDgmcjbzj7m5GjkylDodcMpAc8xtfPE8n3Kok5khB187B/ujntr0U5nSMCY4rxPaxuzbpc0eQPHJY3m7bvessGL7d8+H8EGejKu2WAxKXO+qUAxADGernoHqNNo0ZjmFNmLzplNo1RXfWbSm14iYMzpvdclE2RZHLGR4cnMk6zOGNliWO8mhbVSH/RnvVM645+CPiPRyn5HPaS5ccRtEhhRA0H6pdb++/bnzAujg+0nd2P8sTcOzeVIi8NTo8mZKMh/iytSzVKYF+k6KG7
  template:
    metadata:
      name: git-secrets
      namespace: flux-system
