---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-secrets
  namespace: flux-system
spec:
  encryptedData:
    password: AgA7x3EY7Zj9W4URCrlHblyeHelrx6oKUtU6xrAkkbjJLKxCH03V6AOvz7OikHAlhAyTfSt266w6oRO4u80QDPFB7Vd7FNzD8TDAEBaFqziA2s4bnlCQFLnrwGM1Qx8Cpb7QScO1IuVf50TMQ6OnX3rtPam6C4Vk2B0RHfYrVamc8dxOY12G6fkEeUIOZga1NA4CsAkd7EtjyDy2F7FhSNzgAPAf/XmOZndPu6Gt4jb5f5SU2LqDwPkonPxZIP9+qYZA5H9vDyU3nLYMwTZPHV+GEwIcNssjQPJoKnEoi3U/k66JJ2KOmlCX2BksUK8OFLYR1TuDXwU5gcxyEXSm0Ghj2zTj3sp1br9rJjyWotlKeIt6hKfbLTiurG+YJ0eTbPHePSdJeOdpEbfY2JM46wVPcIZYP97AUR4PC+7HWJb1jVGYh8k1036NmYXb+Rd6aJzqCOZTzecs/QjDPk+OJ0DBA5y07qTvkmhqswWyLxXHXiKTLTnc+Jg1p2A1PKGSYJZJD4r6TAQcpJo1kZHbY3JCLYw9vGwHEPFEmZn5Iavn4SOHaBrVhE+rTHg69Af4H2Dg/wLddYlNApukOWA/EXYa7yFFIQYR6HE0B7Yzk08oGjllIShgB2B0DNz4/ukB5eKePqpIQnOcYmztbkE4kH9W5XSgTXTrvXL1vGspGVNr5sFgQHh0+eERpKUY3h+H3TU43E2z9aakCnN1T4IEJDZdVnKj1ZOlha2R8Fvi9iQOl4rWGfRoTi5y
    username: AgA8vr1V8TW6XYF0c18jpf0HKqIAgzCnlQggycYkJ5S1uVGZAW6negDXPLufzyQndIOduF8a31jWL0F4dK1b5RAqD7+ISAPvbjWggPC6g/I86WCGKBCvbp9yUJ/yvuNIaHjcG37jMKh+6i4UiuoyXfdrHETH9Kz6CQSjlxmPdTCh0SrcoIC1RQar5T85l4FsRUWRN6I2BK6eKh2JUHNRbi6FRWgB3brjY9Z9UCZtCtSu+7V7vTIHndHPra7HC+oJtvVucWJpeUoXNtWWXXfADFjRZFEc2B/s0e0Xb3NaV1AWlIDZAj4vPrA0LBZ+BWFMGszkiNI35kaJtj9x2UetRAtAcRbqjbg5BQeh+iujoj35lkT7/mbwcV7yYkfWVppmJeUkl5WRCIZOnC9GbbX46TYg62SImmAGhg1/nKs7N5LWNg5vrbJhhK+HEau23v5RFNnQbpMnWd4zYX4zpmMeZAlukQF/WrVdBkv4A4gSKEz/F98oeIhssb7HErk+sERtrtASHR6XMoCpEbc9bgt+VLJhqxMXcvez2AqHvryZ2mVT5uXv5u9aFH7rWi2Ncsxw0llWuV2BdE2K4wxc5sSSoZj5tF7fZaQ8z3N1qewb9tVOVpOP+PkjdlcFVSgahRFs1RCmlSvUWm32WD+sVHl8h44zjZUiW+b18XC5/85q+mg8ZqKoLoli+Ky+Ck5PdBrWPacNLulTi0YxCHzzZXY=
  template:
    metadata:
      name: git-secrets
      namespace: flux-system
