---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-secrets
  namespace: flux-system
spec:
  encryptedData:
    password: AgCV9pjiBXuLxEoJJWzReHZstVT7oRElQjiaWyP2UCvXnD0Mfa76ux2VYejWvQp4SPRX3/9QcRL9mNwRekio9zFARTGf1XPYnoTjQctz4lgemLHwGtAuAiHHBGnzD6EO1fLDD9RIad9KzxngW2PsgFRIUS8D9grdQG/M1NRdr0+keIrjotLSY1OTDVXFuQ5xdcG0QXo2xuN01ZSeB2DIq+08wZUj4IW25qkCuEkvs53EVnqF0BuPDN6vN3rLcjd+p9sQGzGRBzyqKdioLlwcuK1aAe0hOSoJIadk0yIp3sk07IeutWfQ9nmDOZ2KXeV2DwtJ4/G9lQb657nyzov99JK5R4niA0a3DXYkE55ro62QLxd+g9ZW1jZe6O4d74tV+m+prkiWEcOTCXKT07NnOnE8Ry29kOM9WmHRDArLDOMixnS9gdoLIpVxoyk+DXgt6Td480uHu2JgkRqJ9ciUglgUh78kVaQzT9ozRtJyd0Lb7z3DHJjRbTcekwjAiR54q42j4nsccup7wYzX1JT07zWj6hQroAPqzfUYXKuih6PDia9DETZEMqb5HkZtJLfb+crqABOgI4AblvG3V6AqvcBg3gDY/Q4xs85kA3HKCdKb4xnmvNqX0Apci6hjWpKX1KqNZVR/Zj/NQUVd4MzXtbMSv+FjRJAAcGjFu6EAOPw8XqaoXjN91Guq7AEjo0wFlKWNoLVMVT5dX/Js1r9aqSZff2BsVNjyBBCJWNNYULql9gzL7lvCok93jgG2MmVG9fMOqrNiMVaIagUXZ5dfXudzXQNvNTFNwzhkD0GwNfo2yo5pGn3y0410lciz7bY=
    username: AgAJirniI3aMrpqpS0T9noK8fOWdBYGjDFQ4xvQS0wQQGOcg42Oo+6JfwuTphP9o46FFj1P8kQpxwMkV9W7YLVnzW/lbQWLVK9MPDT2nVRM/EY8aG/Z6rxXVAiup7mOmmdWZ4PY0BfKUm7TtWSAVsbYmGfE+7CqoXSKRASsY3bdleSL/+yGlp7fIfEAzHVLeXm4MtGtGZTNjr3D0XNxZFcFmj6ApgQ0uC6JB5ps+LxvssjaZGTEmqHBt/1e6rkpi5BYE1qeNpXx+HyqJJShXSxIp+QuDLSNS+GDLlqRzqqoWW3Ei//QeExLeYesotrUg5KHwQQpI0J1kDCESx0ThDsqSBC+QhKaHCJbHs0pQNEKQzuKGi4re3JgwLufQrKCJ9XRqRHE9CkoU6N3Z0PTRErnSJL33qlX61hpVhV1dgtcRO0LyFxAci47uuiULQYA52QEY95W24zrzRnFa1XOGMprv70bnxmPpJEppP0TxaZOWYlzFg850Sx2mNuHRi6DTHAq/VXBwrj/nr45BdLjLPGRBceBQ61g0Ik//Bm0Fm/CtPDOEqzDocngGxsva75xOp6x6AJ85LLmorxHZg3f3ib78wawIjT8c1mokjCy5LjzB9j+67lHunju/63EvnTpKy6VE9cQoJvn1FEP1mu47TQGmxuaTlfu/5YhwPQSDcL5K7QTiZyBIPnKZmfbAjtsFt1owfkEU2Xpse+JycNc=
  template:
    metadata:
      name: git-secrets
      namespace: flux-system
