---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCf2l/fLiJ5FQ+MCR0J0AiSwGzCx+uPyRVPlOJGzzMDil2BQh6DuFByVd0OnVK1Aml81hXBzwx+hbES7XLZ6fHIQkNpaK2kx0Y1rd9tQZjp85I7M2A0T36Ov0XEeESiRm5mfaksojSuvAFo/xeTqGFuGnw1pwH01/76mRr0d2hKYDFAxFvDvI1z9oiol0EM5XvsquwsB6tpDH2SB5Rc5sxVVzIKAjnnmxV7IiBig47S49lLGxu355/tsTZ4Wad3wbUU6CeigzpmkXBb4NO8VIC85h6gsLA4eEvTfWfcRIVhzr6EuApeRdEeWT/bSEWNi4qgDi4RUWmiD8XkwGqD4CbIFj20QvR/50+nIJSVFMEyVCchpe6wQ/SFG9fcxSQ4+tc1Cpn+x+hMCyh2353z1h7HIYAn1wU9Lp4xD/OuPG1gTpg4J5P0VNLYNoz3WwQ0tSs8rm2foKYCnrfx9zNvAnSx/PQg39H7Xe6+W/s7Ny+UiYYyIYvjSBt+BDHT3a5GUfDjgQcylqcveITWDgv7wQDHOG+sRJ/AkmWuQtXXoHlZ2IfYZP4zpZf3iUojxAxZvqznpPAnaBzRHsTg38gGMEFgZSlO3ItD/1jpCK6/UejkOXzWpFySBuW4FPdMINhXQeODkZ2TcKf5fxJvEFRAdrvhqsNO/6sSdvP+dllmvoffsu1p2crfTfa6eOrSNUCDmurlBR/+xOUZ1HfcvakKapk=
    admin-user: AgAWSIrwNwGl6KbGGIQ98yiBW/3RNAzO4DXkomPOwHB1egc40kKkEMlKgkHAWtBfK2gw3o8+UjItqEERdUq+e8n6FGnntultt0Q9DArcVUi7RH+0WN+/nM1hu9DLzE5lTiPexVUTQrO6zg/s7VLwmjLAbtKK9I5vYuxtngC1tQb+juZeN5u3WLd8libYaZ5bnOBJD60HTmn/E/Xj3kKZMoRRn6cQOx9aYjHFIL6O0kSgyRbZe4mIq2NEWDzLfovNOpnQ1JNN04fSnx7l3jfHCMsChnz4Ef/1cQ4n8b/0H54/9b8TkcJYuNUN8ajVdGSdHWlos9v9hNeW5DuSfKIfk6Fe9h9LVr2LB6nb+rX8exTF4eSITtUu2chDREyHsfgSoLbsH8u8TTumX2W/zVOM/Kqjh+3BDYRg0zsUhR4benaE/2Orh5KCIvTKTMZwOTinwVgfDXNAGcE++eI3KvPp/dx9K2rQ5MhbWZ4E62aloLY2shl+Cu8DlV/JUps8i1ST0/7w9DZ0aOLG+Qd4/S2DMXBHjhtRL/pJx/l4xQWjbGpw5CCMWQ74BUsdFz3gAjZu/f3kR/YsD4iAfitvh0wDuvNntc/f6wlFdZGdG5ynAaHrsYQsjMUD/vwcHC1eduDRYQmUeVrVq0zZTxgX7kJoXFYHAIWU/IUWL5pKfFvFYjaaroh1vnykbdsHu+tUyanZt7wSMW5Pyg==
  template:
    metadata:
      name: monitoring-grafana
      namespace: monitoring
