---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openclaw-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/openclaw-rocks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openclaw-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: openclaw-operator
      sourceRef:
        kind: HelmRepository
        name: openclaw-operator
  interval: 1h0m0s
  releaseName: openclaw-operator
  targetNamespace: openclaw-operator-system
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace